/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modulos.ListaMetas;
import modulos.ListaTarefas;

/**
 *
 * @author usuario
 */
public class ListarMetas extends javax.swing.JFrame {

    /**
     * Creates new form ListarMetas
     */
    SimpleDateFormat novo = new SimpleDateFormat("dd/MM/yyyy");
    int cont1,realizados1;
    ArrayList<ListaMetas> metas = new ArrayList<>();
    AdicionarMetas controller;
    public ListarMetas(AdicionarMetas add) {
        initComponents();
        this.controller=add;
        carregarMetas();
        progressobarra();
        this.setDefaultCloseOperation(0);
    }

    public ListarMetas() {
        initComponents();
        this.setDefaultCloseOperation(0);
    }
    public void carregarMetas()
    {
        metas = controller.getMetas();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        Collections.sort(metas);
        int contador = metas.size();
        modelo.setNumRows(0);
       
        //System.out.println(estudos.size());
        for(int i=0;i<contador;i++)
        {
            modelo.addRow(new Object[]{
                metas.get(i).getNome(),
                novo.format(metas.get(i).getData()),
                metas.get(i).getObs(),
                metas.get(i).isConcluse(),
            });
        }
        cont1=contador;
       
    }
    private void progressobarra() 
    {
        float porcentagem=((float)realizados1/cont1)*100;
        if(cont1>0) jProgressBar.setValue((int)porcentagem);
        else jProgressBar.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jConcluido = new javax.swing.JButton();
        jVoltar = new javax.swing.JButton();
        jExcluir = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jAlteraData = new javax.swing.JButton();
        jBuscarDatas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Data", "Observação", "CheckList"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jConcluido.setText("Concluído");
        jConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConcluidoActionPerformed(evt);
            }
        });

        jVoltar.setText("Voltar");
        jVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarActionPerformed(evt);
            }
        });

        jExcluir.setText("Excluir");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        jProgressBar.setStringPainted(true);

        jLabel1.setText("Progresso das metas");

        jAlteraData.setText("Alterar Data");
        jAlteraData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlteraDataActionPerformed(evt);
            }
        });

        jBuscarDatas.setText("Buscar");
        jBuscarDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarDatasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAlteraData)
                                .addGap(63, 63, 63)
                                .addComponent(jVoltar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBuscarDatas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jConcluido)))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConcluido)
                    .addComponent(jExcluir)
                    .addComponent(jBuscarDatas))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVoltar)
                    .addComponent(jAlteraData))
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jVoltarActionPerformed

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        int linha_excluir=jTable1.getSelectedRow();
       
        if(linha_excluir!=-1)
        {
            if(controller.getMetas().get(linha_excluir).isConcluse())
            {
                   realizados1--;
            }
            controller.getMetas().remove(linha_excluir);
            cont1--;
            modelo.removeRow(linha_excluir);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        progressobarra();
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConcluidoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        int linha_concluida=jTable1.getSelectedRow();
        if(linha_concluida!=-1)
        {
            controller.getMetas().get(linha_concluida).setConcluse(true);
            //if(!controller.getMetas().get(linha_concluida).isConcluse()) 
            realizados1++;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        
        
        carregarMetas();
        progressobarra();
        
    }//GEN-LAST:event_jConcluidoActionPerformed

    private void jAlteraDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlteraDataActionPerformed
       DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        int linha_alterar_data=jTable1.getSelectedRow();
        if(linha_alterar_data!=-1)
        {
            
            controller.getMetas().get(linha_alterar_data).setData(JOptionPane.showInputDialog("Digite uma data válida: (ex: dd/mm/yyyy)"));
            //if(!controller.getMetas().get(linha_concluida).isConcluse()) 
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        
        
        carregarMetas();
        progressobarra();
    }//GEN-LAST:event_jAlteraDataActionPerformed

    private void jBuscarDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarDatasActionPerformed
        String data_busca = JOptionPane.showInputDialog("Digite uma data para busca: (ex:dd/mm/yyyy)");
        Date a,b;
        ListaTarefas aux = new ListaTarefas() {};
        aux.setData(data_busca);
        b = aux.getData();
        ArrayList<ListaMetas> tarefas_buscadas = new ArrayList<>();
        if(data_busca!=null)
        {
            for(int i=0;i<controller.getMetas().size();i++)
            {
                a = controller.getMetas().get(i).getData();
                if(b.equals(a))
                {
                    tarefas_buscadas.add(controller.getMetas().get(i));
                    
                } 
            }
            
            FrameBusca buscando = new FrameBusca(tarefas_buscadas,data_busca,1);
            buscando.setVisible(true);
            
        }
    }//GEN-LAST:event_jBuscarDatasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarMetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarMetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarMetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarMetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarMetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAlteraData;
    private javax.swing.JButton jBuscarDatas;
    private javax.swing.JButton jConcluido;
    private javax.swing.JButton jExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jVoltar;
    // End of variables declaration//GEN-END:variables
}
